spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp-test?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    root: warn
    com:
      seina:
        test:
          mp:
            dao: trace
  pattern:
    console: -%d%m%n

mybatis-plus:
  mapper-locations:
    - com.seina.test.mp.mapper


